[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
version = "latest"
excluded-patches = "'Minimized playback' 'Announcements' 'Enable debugging' 'Tablet mini player' 'Enable tablet layout'"
