logging-to-file = false        # enables logging of every patch process to a seperate file
enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[Youtube mod]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
apkmirror-arch = "arm-v7a"
version = "latest"
included-patches = "'Remove player controls background'"
excluded-patches = "'Spoof device dimensions' 'Minimized playback' 'Client spoof' 'Enable debugging' 'Announcements' 'Playback speed' 'Old video quality menu' 'External downloads' 'Spoof app version' 'Wide searchbar' 'Hide timestamp' 'Enable tablet layout' 'Tablet mini player' 'Enable old seekbar thumbnails'"
