[YT-Revanced]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
version = "latest"
included-patches = "'Remove player controls background'"
excluded-patches = "'Enable debugging' 'Always repeat' 'Minimized playback' 'Announcements' 'Spoof device dimensions' 'Enable tablet layout' 'Downloads'"

